### ISSUE TITLE
Fix global variable vid_url_list_final

### ISSUE THREAD

**Issue by msolorzano** [meetshah1995/mit-ocw-dl#4]
This variable "vid_url_list_final" must be "video_url_list_final" for making this work.
Also you could consider remove "import os" because is not used and respect PEP8.

What a great project, so helpful, thanks for make it.

**Comment by meetshah1995** [comment]
Variable name updated. Thanks @msolorzano .

I had planned to create separate directories for videos, lectures , assignments etc. but presently its not needed.
